name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Flet
        run: pip install flet

      - name: Prepare main.py
        # ВНИМАНИЕ: Если файл с большой буквы - исправь тут на Подслушка.py
        run: |
          git config --global --add safe.directory '*'
          cp podslushka.py main.py

      - name: Build APK
        # Добавляем --verbose, чтобы увидеть реальную ошибку, если упадет
        run: flet build apk --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Podslushka-App
          path: build/apk/*.apk
