name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Flet
        run: pip install flet

      - name: Prepare main.py
        # Робот копирует твой файл подслушка.py во временный main.py
        run: cp podslushka.py main.py

      - name: Build APK (Auto Yes)
        # Команда yes | заставляет робота отвечать "Да" на все вопросы
        run: |
          yes | flet build apk --product "Подслушка"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Podslushka-App
          path: build/apk/*.apk
