name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Java
        # Это обязательный шаг для сборки Android приложений
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Flet
        run: pip install flet

      - name: Prepare main.py
        run: cp podslushka.py main.py

      - name: Build APK
        # yes | заставляет робота соглашаться со всеми лицензиями Android
        run: |
          yes | flet build apk --product "Подслушка"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Podslushka-App
          path: build/apk/*.apk
